export const newsItems = [
  {
    id: "86f7e437-faa0-11ea-b3de-0242ac130004",
    title: "Apple's New M3 Max Chip Breaks Performance Records",
    description:
      "Apple's latest M3 Max processor shows unprecedented performance in professional workloads, according to independent benchmarks released today.",
    summary:
      "Apple's M3 Max chip delivers 40% faster performance than previous generation while maintaining power efficiency.",
    sentiment_label: "positive",
    sentiment_score: 0.87,
    category: "technology",
    published_at: "2025-04-15T08:32:45Z",
    updatedAt: "2025-04-15T10:15:22Z",
    source: "Indian Express",
    link: "https://indianexpress.com/article/technology/tech-news-technology/apple-m3-max-chip-performance-7654321/",
    image_url: "/news.jpg",
    persons: "Tim Cook, Johny Srouji",
    organizations: "Apple Inc., TSMC",
    locations: "Cupertino, California",
    read_time: 4,
    popularity: 892,
  },
  {
    id: "e4da3b7f-bbce-11ea-a3c9-0242ac130003",
    title: "Google's AI Assistant Gets Major Upgrade with Multimodal Features",
    description:
      "Google has announced a significant update to its AI assistant, featuring new multimodal capabilities that can understand and respond to voice, text, and image inputs simultaneously.",
    summary:
      "Google Assistant now processes multiple input types at once, enabling more natural human-computer interaction.",
    sentiment_label: "positive",
    sentiment_score: 0.76,
    category: "artificial intelligence",
    published_at: "2025-04-18T14:27:19Z",
    updatedAt: "2025-04-18T16:40:33Z",
    source: "Indian Express",
    link: "https://indianexpress.com/article/technology/artificial-intelligence/google-assistant-multimodal-upgrade-8765432/",
    image_url: "/news.jpg",
    persons: "Sundar Pichai, Demis Hassabis",
    organizations: "Google, Alphabet Inc., DeepMind",
    locations: "Mountain View, California",
    read_time: 6,
    popularity: 754,
  },
  {
    id: "1679091c-5ddc-11eb-ae93-0242ac130002",
    title: "India's IT Exports Reach Record $250 Billion for FY 2024-25",
    description:
      "India's information technology sector has achieved a historic milestone, with IT exports crossing $250 billion for the fiscal year 2024-25, according to data released by NASSCOM.",
    summary:
      "Indian IT exports grow 12% year-over-year, reaching $250 billion and creating over 300,000 new jobs.",
    sentiment_label: "positive",
    sentiment_score: 0.92,
    category: "business",
    published_at: "2025-04-10T09:15:00Z",
    updatedAt: "2025-04-10T11:20:15Z",
    source: "Indian Express",
    link: "https://indianexpress.com/article/business/indian-it-exports-record-9876543/",
    image_url: "/news.jpg",
    persons: "N. Chandrasekaran, Debjani Ghosh",
    organizations: "NASSCOM, TCS, Infosys, Wipro",
    locations: "Bengaluru, Hyderabad, Pune",
    read_time: 5,
    popularity: 678,
  },
  {
    id: "8f14e45f-ceea-11ea-b9c9-0242ac130003",
    title: "Major Security Flaw Discovered in Popular Cloud Services",
    description:
      "Cybersecurity researchers have uncovered a critical vulnerability affecting multiple cloud service providers, potentially exposing sensitive data of millions of users worldwide.",
    summary:
      "Security researchers find 'CloudLeak' vulnerability affecting major providers, patches being deployed urgently.",
    sentiment_label: "negative",
    sentiment_score: -0.68,
    category: "cybersecurity",
    published_at: "2025-04-20T16:43:21Z",
    updatedAt: "2025-04-20T18:55:10Z",
    source: "Indian Express",
    link: "https://indianexpress.com/article/technology/cyber-security/cloud-services-vulnerability-1234567/",
    image_url: "/news.jpg",
    persons: "Katie Moussouris, Bruce Schneier",
    organizations: "Microsoft Azure, AWS, Google Cloud",
    locations: "Global",
    read_time: 7,
    popularity: 925,
  },
  {
    id: "c9f0f895-cd4f-11eb-b8b4-0242ac130003",
    title: "SpaceX Successfully Launches First Crewed Mars Mission",
    description:
      "SpaceX has made history with the successful launch of Starship Mars Pioneer, the first crewed mission to Mars, carrying four astronauts on the six-month journey to the red planet.",
    summary:
      "SpaceX's Starship Mars Pioneer mission lifts off successfully, marking humanity's first crewed journey to Mars.",
    sentiment_label: "positive",
    sentiment_score: 0.95,
    category: "space",
    published_at: "2025-04-12T18:30:45Z",
    updatedAt: "2025-04-12T20:45:12Z",
    source: "Indian Express",
    link: "https://indianexpress.com/article/technology/science/spacex-mars-mission-launch-2345678/",
    image_url: "/news.jpg",
    persons: "Elon Musk, NASA Administrator",
    organizations: "SpaceX, NASA, JPL",
    locations: "Cape Canaveral, Florida",
    read_time: 8,
    popularity: 1245,
  },
  {
    id: "a87ff679-a2f3-11eb-bcbc-0242ac130002",
    title: "Semiconductor Shortage Worsens as Taiwan Faces Historic Drought",
    description:
      "The global semiconductor shortage has intensified as Taiwan, home to the world's largest chip manufacturer TSMC, experiences its worst drought in decades, affecting water-intensive chip production.",
    summary:
      "Taiwan's severe drought threatens chip production, potentially extending global semiconductor shortage into 2026.",
    sentiment_label: "negative",
    sentiment_score: -0.78,
    category: "supply chain",
    published_at: "2025-04-17T11:20:33Z",
    updatedAt: "2025-04-17T13:15:40Z",
    source: "Indian Express",
    link: "https://indianexpress.com/article/technology/tech-news-technology/semiconductor-shortage-taiwan-drought-3456789/",
    image_url: "/news.jpg",
    persons: "C.C. Wei, Mark Liu",
    organizations: "TSMC, Intel, Samsung Electronics",
    locations: "Taiwan, Hsinchu",
    read_time: 6,
    popularity: 843,
  },
  {
    id: "d3d9446c-c3e1-11eb-b4a8-0242ac130003",
    title: "India Launches Nationwide Digital Health ID Program",
    description:
      "The Indian government has officially launched its comprehensive Digital Health ID program, aiming to digitize all citizens' health records and streamline healthcare delivery across the country.",
    summary:
      "India's Digital Health ID program goes live nationwide, creating unique health identifiers for all citizens.",
    sentiment_label: "positive",
    sentiment_score: 0.81,
    category: "healthcare",
    published_at: "2025-04-14T08:45:12Z",
    updatedAt: "2025-04-14T10:30:45Z",
    source: "Indian Express",
    link: "https://indianexpress.com/article/india/digital-health-id-program-launch-4567890/",
    image_url: "/news.jpg",
    persons: "Prime Minister, Health Minister",
    organizations: "Ministry of Health and Family Welfare, NHA",
    locations: "New Delhi, India",
    read_time: 5,
    popularity: 567,
  },
  {
    id: "6512bd43-d9ca-11eb-89ac-0242ac130002",
    title:
      "Quantum Computing Breakthrough Solves Complex Protein Folding Problem",
    description:
      "Scientists have achieved a major breakthrough in quantum computing, using a 1,000-qubit quantum processor to solve complex protein folding problems that were previously intractable for classical supercomputers.",
    summary:
      "Quantum computer solves protein folding challenge in hours that would take classical supercomputers centuries.",
    sentiment_label: "positive",
    sentiment_score: 0.89,
    category: "quantum computing",
    published_at: "2025-04-19T15:10:25Z",
    updatedAt: "2025-04-19T17:05:30Z",
    source: "Indian Express",
    link: "https://indianexpress.com/article/technology/science/quantum-computing-protein-folding-5678901/",
    image_url: "/news.jpg",
    persons: "Dario Gil, John Preskill",
    organizations: "IBM Quantum, Caltech, Google Quantum AI",
    locations: "Yorktown Heights, New York",
    read_time: 9,
    popularity: 732,
  },
  {
    id: "c20ad4d7-6fe8-11eb-9661-0242ac130002",
    title: "5G Network Coverage Reaches 85% of Indian Population",
    description:
      "India's 5G rollout has achieved a significant milestone, with network coverage now reaching 85% of the country's population, making it one of the fastest 5G deployments globally.",
    summary:
      "India's 5G coverage hits 85% milestone ahead of schedule, average speeds exceed 750 Mbps in urban areas.",
    sentiment_label: "positive",
    sentiment_score: 0.85,
    category: "telecommunications",
    published_at: "2025-04-16T09:50:15Z",
    updatedAt: "2025-04-16T11:25:40Z",
    source: "Indian Express",
    link: "https://indianexpress.com/article/technology/mobile-tabs/5g-network-coverage-india-6789012/",
    image_url: "/news.jpg",
    persons: "Telecom Minister, TRAI Chairman",
    organizations: "Reliance Jio, Bharti Airtel, VI",
    locations: "India, Delhi, Mumbai, Bangalore",
    read_time: 4,
    popularity: 615,
  },
  {
    id: "d67d8ab4-dd07-11eb-b8bc-0242ac130003",
    title: "Renewable Energy Powers 50% of Global Data Centers",
    description:
      "A new report reveals that renewable energy sources now power 50% of data centers worldwide, marking a significant milestone in the tech industry's efforts to reduce carbon emissions and combat climate change.",
    summary:
      "Half of all data centers globally now run on renewable energy, reducing tech sector's carbon footprint significantly.",
    sentiment_label: "positive",
    sentiment_score: 0.82,
    category: "sustainability",
    published_at: "2025-04-11T13:40:30Z",
    updatedAt: "2025-04-11T15:55:20Z",
    source: "Indian Express",
    link: "https://indianexpress.com/article/technology/tech-news-technology/renewable-energy-data-centers-7890123/",
    image_url: "/news.jpg",
    persons: "Greta Thunberg, Kate Brandt",
    organizations: "Google, Microsoft, Amazon Web Services",
    locations: "Global",
    read_time: 5,
    popularity: 542,
  },
];
